### ISSUE TITLE
Login Page UI Changes

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#23]
1. Change text Intelligence ---> to Intelligent
2. Have the line cover 70%/80% and not strikethrough the entire container under the Iagon logo

**Comment by ptxd** [comment]
3. Forms element white background must contain all contents. Currently signup/forgot password and social media login buttons are outside the container.

**Comment by AkibS** [comment]
We have made the changes and pushed please verify.

**Comment by ptxd** [comment]
Thanks
