### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#24]
Text areas should have a visible border, using the same color and thickness as the input line.

<img alt="alt-text" aria-describedby="field-types-figure-caption-9" src="https://storage.googleapis.com/material-design/publish/material_v_12/assets/0B5ZSepuCX1xOYXNnRjJKVU53Skk/area-states.png">

**Comment by ptxd** [comment]
For the time being follow this background color pattern

The Colour and theme should be as followed (Unless specified otherwise):
Header Colour: RGB(21,35,46)
Sidebar Color:RGB(250,251,252)
Background:RGB(250,251,252)

Will be adjusted once our designer comes on board. I personally like the black and would use the same header and sidebar color as github #24292e

**Comment by ptxd** [comment]
![image](https://user-images.githubusercontent.com/27824585/32707112-80308a4c-c7d6-11e7-962f-69d8c9e9b0a3.png)

Please use this form format for the form design. Header to be green background and card-body to be white background

**Comment by ptxd** [comment]
Change in header background color scheme - 

[Charte_Iagon.pdf](https://github.com/Iagonorg/Iagon-Platform/files/1500593/Charte_Iagon.pdf)

**Comment by AkibS** [comment]
changed as suggested.
