### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#44]
1. Remove remember me
2. Have link setup to be https://www.iagon.com/login
3. Remove the Line
4. Maintain margin between Logo + text and the text-fields
5. Make recaptcha either fit the entire length as the other components or leave it as the picture
6. SignUp and Forgot Password to be underline text anchor tags
7. Login Google = 1 word
8. <u>"Click here to Sign Up"</u>
9. Follow the design as provided:
![image](https://user-images.githubusercontent.com/27824585/34133274-b107d4c4-e408-11e7-9705-74a746bc4e8d.png)
10. Login with username returning error! If login logic requires email, change username text --> email. If login can use both only then say username.

**Comment by AkibS** [comment]
> Maintain margin between Logo + text and the text-fields

**Comment by AkibS** [comment]
Changed as per the suggestion.
