### ISSUE TITLE
React notification

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#46]
1. Make notifications fully white
2. Allow admins to change notification text
3. Follow the example (make it full white):
![image](https://user-images.githubusercontent.com/27824585/34133842-e8e353de-e40b-11e7-9bed-fc853ecc4242.png)

**Comment by VishalWaman** [comment]
1. In Design of notification show IAGON logo and make it full white.

2. We will have a screen in Admin "Notification", where in we will have textbox (max 200) and a Send Button 

3. On click "Send" we will send to all users , There will be no way to see old Notification sent (No Grid)..

4. After 5 sec just close notification.

**Comment by AkibS** [comment]
1. Changed color scheme to white
2. Notification will close automatically after 5 sec.
3. We are not adding logo in notification

please refer attached image
![capture](https://user-images.githubusercontent.com/33049830/34153044-a6c2f092-e4d6-11e7-9c89-51c972dd0477.PNG)
