### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#47]
1. Cancel button on settings not working
![image](https://user-images.githubusercontent.com/27824585/34133986-ddbb62ac-e40c-11e7-8dba-a60a64f07732.png)
2. Sign out text ----> Sign Out.

**Comment by VishalWaman** [comment]
1. White screen after multiple login
2. On click of Cancel redirect to DashBoard

**Comment by AkibS** [comment]
Changed as discussed
