### ISSUE TITLE
Cookies/Cache

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#48]
Cookies or cache is being corrupted hence user login is met with white screen. Another thing to note is that username keeps populating in the username field when you cant login with a username, not sure if this is one of my dev chrome extension issue or due to some other reason.

**Comment by AkibS** [comment]
I have made the changes, please check at after deployment

**Comment by VishalWaman** [comment]
Fixed, added Login Route for Blank page on reopening tab

**Comment by VishalWaman** [comment]
Done
