### ISSUE TITLE
Miner Application

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#49]
1. Country Dropdown unable to select based on the starting letter.

**Comment by ptxd** [comment]
2. "Miners that take place in the development of the platform are paid from the development budget for their time."
--->"Miners that participate in the development of the platform are paid from the development budget for their time."

**Comment by ptxd** [comment]
3. I though we discussed this ---> use popovers for drop-down fields they look neater.

**Comment by VishalWaman** [comment]
1.  Sort country list
2. Tying selection for country

**Comment by AkibS** [comment]
1. Sorted the list with alphabetical order.
2. we can not use popovers here because we want selection and binding.

**Comment by VishalWaman** [comment]
Removed "Select Country", this will filter correctly.

**Comment by VishalWaman** [comment]
Done
