### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ptxd** [Iagonorg/Iagon-Platform#52]
1. Exchange data to be pulled from API 
https://min-api.cryptocompare.com/data/histoday?fsym=ETH&tsym=USD&allData=TRUE
2. Exchange, graphs and cards should not compress on smaller screens, it should flow down below breakpoint 1000px<
3. Iagon account number is not working
![image](https://user-images.githubusercontent.com/27824585/34137168-451ff230-e41e-11e7-8252-efb4659c22b9.png)
4. Mining Status data should be equally distanced
![image](https://user-images.githubusercontent.com/27824585/34137175-56c5c76c-e41e-11e7-9942-0cd546d1903d.png)
5. The donut chart can be bigger and the % sign centered.Replace Ethereum and Iagon with logo, I think the text looks ugly.
![image](https://user-images.githubusercontent.com/27824585/34137224-9574556e-e41e-11e7-90ef-889191b4d036.png)

**Comment by AkibS** [comment]
Point number 1 ,2, 3 are done

**Comment by VishalWaman** [comment]
All done

**Comment by VishalWaman** [comment]
All done
